numpy는 수학적 연산을 위해 쓰이는 패키지

매트릭스 곱, 합, 잘라 쓰기 등 연산 등 전반적으로 쓰이는 패키지

numpy.org 의 getting started 로 수업 진행

In [1]:
!pip install numpy

In [1]:
import numpy as np

In [16]:
a = np.arange(6)
type(b)

numpy.ndarray

In [17]:
a

array([0, 1, 2, 3, 4, 5])

In [18]:
a[1]

1

In [19]:
a[:]

array([0, 1, 2, 3, 4, 5])

In [21]:
a[np.newaxis, : ] #np.newaxis 는 새로운 차원을 만들겠다는 것, 
#보면 앞뒤로 [] 가 하나씩 더 붙음. 
#이 말인 즉슨 겉의 [] 안에 또다른 []들이 들어감으로써 다른 차원이 추가된다는 것.

array([[0, 1, 2, 3, 4, 5]])

In [22]:
a2 = a[np.newaxis, :] 
a2.shape #한쪽은 1개, 한쪽은 6개의 매트릭스

(1, 6)

In [23]:
a.shape

(6,)

파이썬의 List와 넘파이의 array는 다르다. array가 활용도가 높다

In [25]:
b = [0, 1, 2, 3, 4]
print(type(a))
print(type(b))

<class 'numpy.ndarray'>
<class 'list'>


In [27]:
a = np.array([[1, 2, 3, 4], [5, 6,7, 8], [9, 10, 11, 12]])
a  # 3*4 행렬인 셈. 2차원

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [28]:
a[0,1] # 0번쨰 행 1번쨰 열 값을 가져옴.

2

In [29]:
a[0] # 0번째 행값을 보두 가져온다

array([1, 2, 3, 4])

In [30]:
a[,1]

SyntaxError: invalid syntax (3819423678.py, line 1)

In [31]:
a[:,1]

array([ 2,  6, 10])

In [32]:
a = np.array([1, 2, 3])

In [33]:
a

array([1, 2, 3])

In [35]:
np.zeros(2) # array를 매번 입력하여 만들기 어려우니, zero로 가득 채운다는 것

array([0., 0.])

In [37]:
np.ones(3)

array([1., 1., 1.])

In [40]:
np.empty(4) # 아무값이나 나오네?

array([2.12199579e-314, 3.56040677e-307, 5.47424736e-321, 1.33009382e-278])

In [39]:
np.random(3)

TypeError: 'module' object is not callable

In [41]:
np.arange(2,9,2) # 2부터 시작해서 9이전까지 만드는데 2칸씩 점프한다

array([2, 4, 6, 8])

In [42]:
np.linspace(0, 10, num=5)
#1부터 10까지의 수중 다섯개로 어레이를 구성하라, 단 간격은 동일케 하라

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

특이점은 그냥 0이랑 1 찍어주지 0. 1. 으로 float으로 찍어준다는 것. 바꾸고 싶으면 아래처럼

In [45]:
x = np.ones(2, dtype=np.int64) # 왜 하필 int도 아니고 int64냐
x

array([1, 1], dtype=int64)

### 정렬

In [46]:
arr = np.array([2, 5, 9, 1, 10, 42, 27, 6, 10])

In [47]:
arr

array([ 2,  5,  9,  1, 10, 42, 27,  6, 10])

In [48]:
np.sort(arr) # 정렬해준다

array([ 1,  2,  5,  6,  9, 10, 10, 27, 42])

In [49]:
arr = np.sort(arr)
arr

array([ 1,  2,  5,  6,  9, 10, 10, 27, 42])

In [78]:
arr2 = np.sort(arr)[::-1] # 역순 정렬
arr2

array([42, 27, 10, 10,  9,  6,  5,  2,  1])

### argsort : 정렬하되 정렬한 인덱스를 반환한다.

In [51]:
x = np.array([3, 1, 2])
np.argsort(x)

array([1, 2, 0], dtype=int64)

In [55]:
y = np.array([[2, 4], [1, 3]])
y

array([[2, 4],
       [1, 3]])

In [58]:
np.sort(y, axis=0) # aixs=0 은 열방향을 기준으로 정렬한다는 것

array([[1, 3],
       [2, 4]])

In [59]:
np.argsort(y, axis=0)

array([[1, 1],
       [0, 0]], dtype=int64)

### lexsort : 2행 이상일 경우, 첫행으로 정렬하여 인덱스 반환 후, 다음 행으로 정렬하여 반환된 인덱스를 재반환
이게 어디에 쓰이지?

In [63]:
A = np.array([2, 5, 1, 8, 3])
B = np.array([9, 0, 3, 2, 1])
print(np.argsort(A))
print(np.lexsort((A,B)))
# 어디에 쓰이는지 아직 잘 모르겠다

[2 0 4 1 3]
[1 4 3 2 0]


### serchsorted : 지정값이 삽입되어야 할 위치를 반환

In [64]:
print(np.searchsorted([1,2,3,4,5], 3))
print(np.searchsorted([1,2,3,4,5], 3, side='right'))
print(np.searchsorted([1,2,3,4,5], [-10, 10, 2, 3]))

2
3
[0 5 1 2]


### partition : 배열의 왼쪽(오른쪽)에 k 개의 가장 작은(큰) 값 배치 나머지 랜덤

In [74]:
C = np.array([3, 0, 5, 7, 10, 2])
print(np.partition(C,2)) # k = 2, 가장 작은값 2개를 왼쪽 정렬

[ 0  2  3  7 10  5]


In [75]:
print(np.partition(C,-2)) # k = -2, 가장 큰 값 2개를 오른쪽 정렬

[ 0  2  3  5  7 10]


### concatenate : array 합치기

In [79]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 9])

In [85]:
np.concatenate((a,b)) # 요소가 두개로 합쳐짐. 각각 1차원 array로 파악되어서 그런듯

array([1, 2, 3, 4, 5, 6, 7, 9])

In [81]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [82]:
x

array([[1, 2],
       [3, 4]])

In [83]:
y

array([[5, 6]])

In [86]:
np.concatenate((x,y)) # 그냥 쓰면 행을 붙이게 됨

array([[1, 2],
       [3, 4],
       [5, 6]])

In [87]:
np.concatenate((x,y), axis=0) #행 기준으로 위와 동일

array([[1, 2],
       [3, 4],
       [5, 6]])

In [89]:
np.concatenate((x,y), axis=1) #열 기준으로 합치려 하면 행렬 수가 안 맞아서 에러뜸

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

### 차원 보기

In [91]:
array_example = np.array([[[0, 1, 2, 3], # [[[ 으로 3차원
                           [4, 5, 6, 7]],  안에 [ , [ 2줄 있고, 그 안에는 4개 그래서 3, 2, 4

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])  #이게 3차원 구조임

In [93]:
array_example.ndim #차원을 보자

3

In [94]:
array_example.size #개체수를 보자

24

In [95]:
array_example.shape #형태를 보자 3*2*4의 3차원 , 가장 바깥 쪽에 있는 수 3부터 센다. 그 안에 원소단위

(3, 2, 4)

### shape 바꾸기

In [96]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [97]:
a.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [99]:
a.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [100]:
a.reshape(4,2) # 개체수가 안 맞아서 에러, 6개 밖에 없는데 8개 있는 테이블 만들라니 에러

ValueError: cannot reshape array of size 6 into shape (4,2)

In [103]:
np.reshape(a, newshape=(2, 3), order='A')

array([[0, 1, 2],
       [3, 4, 5]])

### shape

In [104]:
a

array([0, 1, 2, 3, 4, 5])

In [105]:
a.shape

(6,)

In [106]:
a2 = a[np.newaxis,:] # 차원을 하나 더 추가 기존 [] 를 덮어씌우는 []가 생김, 뒤에 : 는 모든열에 적용한다는 것
a2

array([[0, 1, 2, 3, 4, 5]])

In [107]:
a2.shape

(1, 6)

In [108]:
a3 = a[np.newaxis, :3] # 3열만 가져와서 차원 추가
a3

array([[0, 1, 2]])

In [110]:
a4 = a[:,np.newaxis] # 
a4

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

### indexing and slicing

In [3]:
data = np.array([1, 2, 3])

In [4]:
data

array([1, 2, 3])

In [7]:
data[2]

3

In [5]:
data[0:2]

array([1, 2])

In [6]:
data[1:]

array([2, 3])

In [8]:
a = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

In [9]:
a<5

array([[ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [12]:
a [ a < 5 ]

array([1, 2, 3, 4])

In [13]:
a [ a >= 5]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [14]:
a [ a % 2 == 0]

array([ 2,  4,  6,  8, 10, 12])

In [16]:
a [ ( a > 2 ) & ( a < 11 ) ]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
a = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
b = np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))


In [19]:
list(zip(b[0], b[1])) # 5보다 작은 애들 중에 0이 아닌애들 좌표

[(0, 0), (0, 1), (0, 2), (0, 3)]

### How to create an array for existing data

In [2]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [3]:
arr1 = a[3:8]

In [4]:
arr1

array([4, 5, 6, 7, 8])

In [6]:
a1 = np.array([[1, 1],
              [2, 2]])
a2 = np.array([[3, 3],
              [4, 4]])

In [10]:
np.vstack((a1, a2))   #이런 게 있다 정도로만 기억해두면 됨. 필요하면 찾아볼 수 있는 수준으로

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [8]:
np.concatenate((a1, a2), axis=0)  #vstack 보단 concatenate를 더 빈번하게 씀

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [11]:
np.concatenate((a1, a2), axis=1)

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [12]:
x = np.arange(1, 25).reshape(2, 12)

In [13]:
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [15]:
np.hsplit(x,3)  # 위에서 입력한 x를 3개의 array로 잘라서 씀. 별로 쓸 일 없는 듯.

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [17]:
np.hsplit(x, (3, 4)) #인덱스에 해당하는 부분을 자름.

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

# 여기서부터 중요하다

In [18]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [19]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
a[2, :]

array([ 9, 10, 11, 12])

In [22]:
a[:,2]

array([ 3,  7, 11])

In [23]:
b1 = a[0,:]
b1

array([1, 2, 3, 4])

In [24]:
b1[0] = 99

In [26]:
a  # 원본 a 에서 b를 추출해서 가공했는데 원본까지 바뀌어 버림. 이게 무슨 일이람

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [27]:
b2 = a.copy() # a의 가피본 b2 생성

In [28]:
b2[1,1] = 7
b2

array([[99,  2,  3,  4],
       [ 5,  7,  7,  8],
       [ 9, 10, 11, 12]])

In [29]:
a # b2 세부항목을 바꿔도 a 는 안바뀌게 됨

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### basic array operations

In [30]:
data = np.array([1, 2])

In [31]:
ones = np.ones(2, dtype = int)

In [32]:
data + ones

array([2, 3])

In [33]:
a = np.array([1, 2, 3, 4])

In [34]:
a.sum()

10

In [35]:
b = np.array([[1, 1],[2, 2]])

In [36]:
b.sum()

6

In [39]:
b.sum(axis=0)  # axis=0은 행을 기준. 행을 기준으로 열끼리 합친다고? 행을 옮겨가면서 더한다.

array([3, 3])

In [41]:
b.sum(axis=1) # 좀 헷갈리게 만들었네

array([2, 4])

### More useful array operations

In [42]:
data.max()

2

In [43]:
data.sum()

3

In [44]:
data.min()

1

In [46]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [47]:
a.min()

0.05093587

In [49]:
a.min(axis=0) # 행 중에서 가장 작은애를 찾는다? 실제는 같은 열에서 작은 애를 찾는 결과. 이정도면 axis=0은 열기준으로 외우는게 낫지않을까?

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

### Creating matrics

In [50]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [51]:
data[0, 1]

2

In [52]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [53]:
data[0:2, 0]

array([1, 3])

In [55]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [56]:
data = np.array([[1, 2], [5, 3], [4, 6]])
data

array([[1, 2],
       [5, 3],
       [4, 6]])

In [57]:
data.max(axis=0) #행을 바꿔가면서 최대값 찾는다고 이해

array([5, 6])

In [58]:
data.max(axis=1) #열을 바꿔가면서 최대값을 찾는다고 이해

array([2, 5, 6])

In [59]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + ones

array([[2, 3],
       [4, 5]])

In [60]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

### How to get unique items and counts

In [61]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [62]:
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [63]:
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


### Transposing and reshaping a matrix

In [64]:
data.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [66]:
arr = np.arange(6).reshape((2, 3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [67]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [68]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

### How to reverse an array

In [69]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [70]:
reversed_arr = np.flip(arr)

In [71]:
print('Reversed Array: ', reversed_arr)

Reversed Array:  [8 7 6 5 4 3 2 1]


In [72]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [73]:
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [74]:
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [75]:
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [76]:
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [77]:
arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


## Reshaping and flattening multidimensional arrays

In [78]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [79]:
x.flatten() # 1차원으로 평탄화

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [81]:
a1 = x.flatten() # x를 평탄화하여 a1에 저장
a1[0] = 99 # 첫번째 값을 99로바꿈
print(x)
print(a1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[99  2  3  4  5  6  7  8  9 10 11 12]


In [82]:
a2 = x.ravel()  # flattne은과 ravel의 차이는 ravel은 원본 데이터 x까지 바꿔버림
a2[0] = 98
print(x)  # flatten 케이스와 달리 x의 맨 앞 값마저 98로 바뀌어 있음
print(a2)  

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[98  2  3  4  5  6  7  8  9 10 11 12]
